[book]
authors = ["Reid"]
language = "en"
multilingual = false
src = "src"
title = "my-test-for-mdbook"
description = "The example book covers examples."

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]

[output.html.search]
limit-results = 15
